Fallback if issuerInt is missing
I bumped into the following error when I used your script - thank you for this handy tool! After some digging this fix seems a valid solution to the problem.

```python
Traceback (most recent call last):
  File "backup_freetop_codes.py", line 37, in <module>
    'issuer': token["issuerInt"]
KeyError: 'issuerInt'
```